FROM debian:buster

RUN apt-get update -qq && apt-get install -y curl gnupg2

RUN curl -sS https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add -
RUN echo "deb http://apt.postgresql.org/pub/repos/apt/ buster-pgdg main" | tee  /etc/apt/sources.list.d/pgdg.list

RUN apt-get update -qq && apt-get install -y zip cron postgresql-client-12

RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
RUN unzip awscliv2.zip
RUN ./aws/install --bin-dir /usr/bin

COPY ./scripts/run-scheduler.sh scripts/run-scheduler.sh
COPY ./scripts/backup-postgres.sh scripts/backup-postgres.sh
RUN chmod +x scripts/run-scheduler.sh scripts/backup-postgres.sh

COPY ./scripts/scheduler-crontab /etc/cron.d/scheduler
RUN chmod +x /etc/cron.d/scheduler
RUN crontab /etc/cron.d/scheduler

CMD ["/scripts/run-scheduler.sh"]
