version: '3.4'

services:
  app:
    build:
      context: .
    command: 'rails s -b 0.0.0.0'
    depends_on:
      - postgres
      - scheduler
    ports:
      - "3005:3000"
    volumes:
      - .:/app
      - gem_cache:/usr/local/bundle/gems
    env_file: .env

  postgres:
    image: postgres:12.6
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file: .env

  scheduler:
    build:
      context: .
    command: '/scripts/run-scheduler.sh'
    depends_on:
      - postgres
    env_file: .env

volumes:
  gem_cache:
  db_data:
  node_modules:
